### PR TITLE
Example of connection with the game

### PR DESCRIPTION
**Pull request by dungbik**
**Example of connection with the game**

### CODE REVIEW

**Review by SHyeMin — COMMENTED** [review]
Confirmed the new PR

**Comment by blacksg** [comment]
New source and header files should be renamed into "rhythm.c" and "rhythm.h".
Except for that, it looks nice.

**Comment by dungbik** [comment]
> New source and header files should be renamed into "rhythm.c" and "rhythm.h". Except for that, it looks nice.

**I'm done fixing it.**

**Comment by blacksg** [comment]
> > New source and header files should be renamed into "rhythm.c" and "rhythm.h". Except for that, it looks nice.
> 
> **I'm done fixing it.**

Confirmed the correction. Thank you.

**Comment by SHyeMin** [comment]
Is it okay to merge the new PR?

**Pull request merged**
